spring.application.name=CRUD

spring.datasource.url=jdbc:postgresql://localhost:5432/crud_db
spring.datasource.username=postgres
spring.datasource.password=211204

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true